name: 更新 BPB 面板数据
on:
  push:
    branches: [ main ]
  workflow_dispatch: # 手动运行
  schedule: # 每日更新
    - cron: '0 16 * * *' # UTC+8 的 00:00

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 安装 Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 安装依赖
        run: pip3 install requests beautifulsoup4 selenium packaging

      - name: 运行脚本
        run: python "Get.py"

      - name: 推送至邮箱
        env:
           ADQQ: ${{ secrets.AD_EMAIL }}
           PASSWORD: ${{ secrets.PASSWORD }}
           ADOST: ${{ secrets.AD_ONE_SIX_THREE }}
           SENDER: ${{ secrets.SENDER }}
        run: python "Send.py"

      - name: 删除临时文件
        run: rm -rf 1.txt 2.txt OK.txt